DROP DATABASE IF EXISTS `E_MilhoesDB`;
CREATE DATABASE  `E_MilhoesDB`;

CREATE TABLE `E_MilhoesDB`.`2022` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `n1` INT NOT NULL,
  `n2` INT NOT NULL,
  `n3` INT NOT NULL,
  `n4` INT NOT NULL,
  `n5` INT NOT NULL,
  `e1` INT NOT NULL,
  `e2` INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;